### ISSUE TITLE
ImportError: No module named biom

### ISSUE THREAD

**Issue by HuangRuocheng** [thomasgurry/amplicon_sequencing_pipeline#1]
Dear Developers,

I'm trying this pipeline. However, when I typed 

    python ./scripts/Master.py -h 

, it turned out:

    Traceback (most recent call last):
      File "./scripts/Master.py", line 18, in <module>
        import QualityControl as QC
      File ".../amplicon_sequencing_pipeline/scripts/QualityControl.py", line 17, in <module>
        import Formatting as frmt
      File ".../amplicon_sequencing_pipeline/scripts/Formatting.py", line 13, in <module>
        import biom
    ImportError: No module named biom

I'm using Python 2.7.10,  and I can't find package biom online or in this pipeline. 

Could you give a help? Thanks very much!

Huang Ruocheng

**Comment by cduvallet** [comment]
Hello! Thanks for raising this.

You can get the `biom` module here: http://biom-format.org/

That said, I don't think the pipeline actually uses biom format in any of the default functions - it's only included as optional functions in the `Formatting.py` module (to convert traditional text file OTU tables into biom format). So if you're having a hard time installing it, I'm pretty sure you can comment out the import calls in `Formatting.py` without breaking anything...

Because we mostly use this pipeline on our in-house clusters, we haven't given much instruction for installation. Apologies in advance for difficulties here - installing this pipeline is something we know may be difficult, and will hopefully get a chance to simplify someday!
